global:
  runner: 
    containers:
    - image: razorci/golang:1.14
      environment:
      - DB_CONNECTION=mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:27017/${DB_NAME}
      - DB_NAME=${DB_NAME}
    - image: bitnami/mongodb:4.4.1
      environment:
      - MONGODB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MONGODB_DATABASE=${DB_NAME}
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASS}

tasks:
  build:
    steps: 
    - checkout
    - docker/build:
       image: saurabh3460/todo-app
       # push: true
       tags: ["${CI_COMMIT_SHA}", "latest"]
       dockerfile: server/Dockerfile
       context: server
    - commands:
      - |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.42.1/trivy_0.42.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.42.1_Linux-64bit.deb
          trivy image --format template --template "@junit.tpl" -o junit_report.xml  saurabh3460/todo-app1:latest
    - reports/junit:
        paths: ["junit_report.xml"]
       
