global:
  runner: 
    containers:
    - image: razorci/golang:1.14  # primary container will be used by all steps
    - image: bitnami/mongodb:4.4.1 # secondary container will be running in background
      environment:
      - MONGODB_ROOT_PASSWORD=adminpass
      - MONGODB_DATABASE=test
      - MONGODB_USERNAME=appuser
      - MONGODB_PASSWORD=apppass
tasks:
  scan:
    steps:
    - checkout
    - commands:
      - | 
        curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x ./snyk
        docker build -t saurabh3460/todo-app1:${CI_COMMIT_SHA:0:8} -f server/Dockerfile server/
        ./snyk container monitor -d saurabh3460/todo-app1:${CI_COMMIT_SHA:0:8} --file=server/Dockerfile || true


