global:
  runner: 
    containers:
    - image: razorci/golang:1.14
      environment:
      - DB_CONNECTION=mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:27017/${DB_NAME}
      - DB_NAME=${DB_NAME}
    - image: bitnami/mongodb:4.4.1
      environment:
      - MONGODB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MONGODB_DATABASE=${DB_NAME}
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASS}

tasks:
  test:
    steps:
    - checkout
    - commands:
      - |
        # Installing synk
        curl --compressed https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x ./snyk

        docker build -t saurabh3460/todo-app:${CI_COMMIT_SHA:0:8} -f server/Dockerfile server/
        ./snyk container monitor -d saurabh3460/todo-app:${CI_COMMIT_SHA:0:8} --file=server/Dockerfile
        
        
