# stage - build
FROM golang:1.14.4-stretch as build
WORKDIR /code
# copy package manifest(less-frequent changing layer)
COPY go.mod go.sum ./
RUN go mod download
# copy code (frequent changing layer)
COPY . .
# generate binary artifact
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/todo
EXPOSE 8080
ENTRYPOINT ["todo"]
USER 1001